flags:
  citeproc:
    executable: true
    icu: false
resolver: lts-18.10
extra-deps:
- git: https://github.com/jgm/pandoc-types.git
  commit: aed20ed845edf98110995217d66d4627a1824eea
ghc-options:
  "$locals": -fhide-source-paths
